<a href="https://colab.research.google.com/github/mynkbtp/Neural_Networks_Python/blob/main/NN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
"""
So, basically, every output @ the neuron = weight*input + bias. Each neuron has some bias which gets
added in the output calculation
"""
inpt=[1,10,20,2] # 4 input neurons
wts=[0.2,0.87,-0.62,0.42] # each incoming neuron from each of input node to output node has one wt. associated with it.
# So, basically 4 nuerons feeds 1 output neuron
bias = 5.8

#output at the neuron
opt=inpt[0]*wts[0]+inpt[1]*wts[1]+inpt[2]*wts[2]+inpt[3]*wts[3] + bias
print("output[Single Neuron]:",opt)

output[Single Neuron]: 3.139999999999998


**Coding a NN Layer**

4 neurons of input layer are connected to 3 opt. layer neurons [Fully connected]

Each opt neuron has 4 incoming wts ( 1 from each inpt layer neuron). Therefore, 

4x3 = 12 connections [Total connection in NN]

In [2]:
inpt = [2,10,3,0.8]

wt1=[0.2,0.8,-0.5,1.0] # wt1 means 1st opt neuron weights
wt2=[0.5,-0.91,0.26,-0.5] # wt2 means 2nd opt neuron incoming weights
wt3=[-0.26,-0.27,0.17,0.87] # wt3 means 3rd opt neuron incoming weights

# three biases of each of the 3 opt neuron
bias1=2
bias2=3
bias3=0.5
"""3 output neurons means we will have 3 output in a list"""
opt = [inpt[0]*wt1[0] + inpt[1]*wt1[1] + inpt[2]*wt1[2] + inpt[3]*wt1[2] + bias1,
       inpt[0]*wt2[0] + inpt[1]*wt2[1] + inpt[2]*wt2[2] + inpt[3]*wt2[2] + bias2,
       inpt[0]*wt3[0] + inpt[1]*wt3[1] + inpt[2]*wt3[2] + inpt[3]*wt3[2] + bias3
      ]
print("output of the 3 neurons:\n",opt)
      



output of the 3 neurons:
 [8.5, -4.111999999999999, -2.074]


So, if want to change the output of the neurons and bring it to certain numbers, you can only tune **weights and biases** to influence output values.

In [3]:
# Optimizing above code
inpt = [2,10,3,0.8]
wts = [[0.2,0.8,-0.5,1.0],
       [0.5,-0.91,0.26,-0.5],
       [-0.26,-0.27,0.17,0.87]
      ]
biases=[2,3,0.5]

print("4 input are: ",inpt)

for neuron_wts,neuron_bias in zip(wts,biases):
  print("printing wts and biases")
  print(neuron_wts,neuron_bias)
  for n_inpt,wt in zip(inpt,neuron_wts):
    print("printing inpt and wts")
    print(n_inpt,wt)
  print("----------------------------------")  

layer_output=[]
for neuron_wts,neuron_bias in zip(wts,biases):
  n_output=0
  for n_inpt,wt in zip(inpt,neuron_wts):
    n_output+=n_inpt*wt
  n_output+=neuron_bias
  layer_output.append(n_output)
print("-----Layer output--------")
print(layer_output)

4 input are:  [2, 10, 3, 0.8]
printing wts and biases
[0.2, 0.8, -0.5, 1.0] 2
printing inpt and wts
2 0.2
printing inpt and wts
10 0.8
printing inpt and wts
3 -0.5
printing inpt and wts
0.8 1.0
----------------------------------
printing wts and biases
[0.5, -0.91, 0.26, -0.5] 3
printing inpt and wts
2 0.5
printing inpt and wts
10 -0.91
printing inpt and wts
3 0.26
printing inpt and wts
0.8 -0.5
----------------------------------
printing wts and biases
[-0.26, -0.27, 0.17, 0.87] 0.5
printing inpt and wts
2 -0.26
printing inpt and wts
10 -0.27
printing inpt and wts
3 0.17
printing inpt and wts
0.8 0.87
----------------------------------
-----Layer output--------
[9.7, -4.72, -1.5139999999999998]


- **Weights** : weights basically changes the magnitude of a  value.
- **Bias** : Bias **offsets** the value by certain margin.

Example follows.

In [4]:
a1 = 0.5
weight = -0.8
bias = 0.8
print("Effect of weight and bias on a value")
print("--- Weight effects---")
print(a1*weight)
print("----- Bias effects----")
print(a1+bias)

Effect of weight and bias on a value
--- Weight effects---
-0.4
----- Bias effects----
1.3


In [5]:
"""Using Dot PRODUCT"""
import numpy as np

inpt = [2,10,3,0.8]
wts = [[0.2,0.8,-0.5,1.0],
       [0.5,-0.91,0.26,-0.5],
       [-0.26,-0.27,0.17,0.87]
      ]
bias=[2,3,0.5]
print("Input shape:",np.array(inpt).shape)
print("Weights shape:",np.array(wts).shape)
print("-------- printing layer output using DOT Product ---------------")
layer_opt = np.dot(wts,inpt)+bias # in np.dot---> weights should come first since- #cols of mtx2 == #rows of mtx1

print(layer_opt)

Input shape: (4,)
Weights shape: (3, 4)
-------- printing layer output using DOT Product ---------------
[ 9.7   -4.72  -1.514]


**Batch Input Processing**

Consider a scenario, where we are taking input from 4 sensors, **BUT** @ 10 different instance of time, say, t1, t2, t3......t10.

This will create [10,4] shaped matrix.

Instead of passing each input one by one and calculating output, we can pass input in batches, say **batch=3** i.e. 3 inputs are passed at a time and output is calculated for them at once.



In [6]:
"""4 input neurons, 3 output neurons"""
# batch input
input=[[2,1,0.5,4.2],[3,0.33,-0.2,12],[0.8,5,4,10]]
print("Batch input: ",input)

wts = [[0.2,0.8,-0.5,1.0],
       [0.5,-0.91,0.26,-0.5],
       [-0.26,-0.27,0.17,0.87]
      ]
bias=[2,3,0.5]

print("input shape: ",np.array(input).shape)
print("weights shape: ",np.array(wts).shape)
print("Transpoing weights inorder to perform dot product:\n",np.array(wts).T)
output = np.dot(input,np.array(wts).T)+bias
print("--------output------------\n",output)


Batch input:  [[2, 1, 0.5, 4.2], [3, 0.33, -0.2, 12], [0.8, 5, 4, 10]]
input shape:  (3, 4)
weights shape:  (3, 4)
Transpoing weights inorder to perform dot product:
 [[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]
--------output------------
 [[ 7.15    1.12    3.449 ]
 [14.964  -1.8523 10.0369]
 [14.16   -5.11    8.322 ]]


**2-Layer Neural Network**

- 4 input layer Neuron
- First Layer: 3 output neurons
- Second Layer: 3 output neurons
- taking BATCH INPUT


In [7]:
"""4 input neurons, 3 output neurons"""
# batch input
input=[[2,1,0.5,4.2],[3,0.33,-0.2,12],[0.8,5,4,10]]
print("Batch input: ",input)

layer1_wts = [[0.2,0.8,-0.5,1.0],
       [0.5,-0.91,0.26,-0.5],
       [-0.26,-0.27,0.17,0.87]
      ]
layer1_bias=[2,3,0.5]

print("------------------------------------Layer1 calculation-------------------------------------")
print("input shape: ",np.array(input).shape)
print("weights shape: ",np.array(layer1_wts).shape)
print("Transpoing weights inorder to perform dot product:\n",np.array(layer1_wts).T)
layer1_output = np.dot(input,np.array(layer1_wts).T)+layer1_bias
print("--------layer_1 output------------\n",layer1_output)

"""Layer2 has 3 neurons -"""
layer2_wts = [[0.3,0.8,-0.5],
       [0.05,-0.1,0.36],
       [-0.126,-0.7,0.17]
      ]
layer2_bias=[5,1,0.43]
print("-----Layer 1 output will be input for layer2-------")
print("------------------------------------Layer2 calculation-------------------------------------")
print("layer1 output shape:",np.array(layer1_output).shape)
print("weights shape: ",np.array(layer2_wts).shape)
layer2_output=np.dot(np.array(layer1_output),np.array(layer2_wts))+layer2_bias
print("------------layer_2 output-------------\n",layer2_output)




Batch input:  [[2, 1, 0.5, 4.2], [3, 0.33, -0.2, 12], [0.8, 5, 4, 10]]
------------------------------------Layer1 calculation-------------------------------------
input shape:  (3, 4)
weights shape:  (3, 4)
Transpoing weights inorder to perform dot product:
 [[ 0.2   0.5  -0.26]
 [ 0.8  -0.91 -0.27]
 [-0.5   0.26  0.17]
 [ 1.   -0.5   0.87]]
--------layer_1 output------------
 [[ 7.15    1.12    3.449 ]
 [14.964  -1.8523 10.0369]
 [14.16   -5.11    8.322 ]]
-----Layer 1 output will be input for layer2-------
------------------------------------Layer2 calculation-------------------------------------
layer1 output shape: (3, 3)
weights shape:  (3, 3)
------------layer_2 output-------------
 [[ 6.766426   4.1937    -2.15547  ]
 [ 8.1319356  6.1306    -6.012555 ]
 [ 7.943928   7.0136    -7.07486  ]]


**OOPs code - NN layers**

In [8]:
np.random.seed(0)
# 4 input neurons at 3 instance of time --- passed in batch
X=[[2,1,0.5,4.2],[3,0.33,-0.2,12],[0.8,5,4,10]]

class Dense_NN:
  # n_inputs--> # of input neurons
  # n_neurons--> # of output neurons in next layer
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.10*np.random.randn(n_inputs,n_neurons)
    self.bias = np.zeros((1,n_neurons))
  
  def forward(self,inputs):
    self.output = np.dot(inputs,self.weights) + self.bias

print("Layer1 has 3 output neurons")
layer1 = Dense_NN(4,3)
layer1.forward(X)
print("layer1 output:\n",layer1.output)

# layer2 has 5 output neurons
print("layer2 has 5 output neurons")
layer2 = Dense_NN(3,5)
layer2.forward(layer1.output)
print("layer2 output:\n",layer2.output)

Layer1 has 3 output neurons
layer1 output:
 [[0.79685558 0.31971768 0.70365374]
 [1.07688161 0.35755601 2.00856381]
 [2.05220466 1.04929226 1.00264607]]
layer2 has 5 output neurons
layer2 output:
 [[ 0.11491082 -0.03251765  0.16777467 -0.15737156  0.14317368]
 [ 0.24824672 -0.1247717   0.47315481 -0.34746954  0.19345604]
 [ 0.22132577 -0.01659273  0.22904627 -0.34522785  0.37978726]]


**Activation Functions**


In [13]:
class Activation_ReLU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs) #RELU

print("layer2 actual output:\n",layer2.output)
activtn2 = Activation_ReLU()
print("---Activating layer2 output with RELU-----")
activtn2.forward(layer2.output)
print(activtn2.output)

layer2 actual output:
 [[ 0.11491082 -0.03251765  0.16777467 -0.15737156  0.14317368]
 [ 0.24824672 -0.1247717   0.47315481 -0.34746954  0.19345604]
 [ 0.22132577 -0.01659273  0.22904627 -0.34522785  0.37978726]]
---Activating layer2 output with RELU-----
[[0.11491082 0.         0.16777467 0.         0.14317368]
 [0.24824672 0.         0.47315481 0.         0.19345604]
 [0.22132577 0.         0.22904627 0.         0.37978726]]
